export const Home = "/";
export const Zarejestrowanie = "/rejestracja"
export const Wszystkie = '/wszystkierestauracje';
export const Kroki = "/zamowienie/:restauracjaid";
export const Restauracja = "/widokrestauracji";
export const Login = "/logowanie";
export const addrest= '/dodanierestauracji';
export const panel = "/zamowieniapanel";
export const Restauracji = "/danarestauracja/:restauracjaid";
